name: Template cleanup
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  cleanup:
    runs-on: ubuntu-latest
    # Skip ALL neuefische org repos (including multiple templates)
    if: "!startsWith(github.repository, 'neuefische/')"
    steps:
      - uses: actions/checkout@v4
      - name: Cleanup notifications
        run: |
          rm -rf .github/workflows/
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Remove template notification workflows'

